SELECT *
  FROM USERS u;

COMMIT;


CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999;

INSERT INTO USERS VALUES(users_seq.NEXTVAL, '22', '22', '222222');

INSERT INTO USERS VALUES(no, 'id', 'password', 'userimage');

select * FROM USERS; 

DELETE FROM USERS WHERE NO=3;

select no, id, password, usersimage FROM USERS where ID='123' AND PASSWORD='123';

UPDATE USERS SET PASSWORD='123' , USERSIMAGE='123' WHERE NO=44;

SELECT * FROM USERS;